apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configurations:
- configuration.yaml
resources:
- app.yaml
configMapGenerator:
  - name: technology-day
    literals:
    - "PYROSCOPE_URL=http://pyroscope.pyroscope:4040"
    - "OTEL_SERVICE_NAME=technology-day"
    - "OTEL_EXPORTER_JAEGER_HTTP_ENDPOINT=http://tempo.tempo:14268/api/traces"
